### ISSUE TITLE
MSFEATS mandatory for content words?

### ISSUE THREAD

**Issue by dan-zeman** [omagolda/msap-docs#9]
README says: Note that node 5 now doesn't have MS-feats (the last column) and therefore it will be dropped from the MS tree.

Does it mean that every node in the MS tree must have at least one feature? What if there are content words that do not take any features in the language?

**Comment by omagolda** [comment]
We did think about this issue. An orphan pipe is to be used for empty MS-feats for a content node.

From the README:
Note: since the file format is a modified version of UD's CoNLL-U, function words may appear in the final output, their MS-feats column should be `_`. This is in contrast with content words that happen to have no MS-feats that should contain an orphan pipe `|`.
